algoritmo "Maior e Menor"
// Função :  Ler dois números e dizer o maior e o menor
// Autor :   Rafaela Curti
// Data : 29/08/2020
// Seção de Declarações 
var
   num1, num2: inteiro
inicio
      escreva("Digite o primeiro número: ")
      leia(num1)
      escreva("Digite o segundo número: ")
      leia(num2)
      
      se num1 > num2 entao
      escreva("Número 1 é maior", num1)
      senao
      esceva("Número 2 é maior", num2)
      fimse
fimalgoritmo
