algoritmo "Média"
// Função :  Calcular a média de 4 notas apresentadas
// Autor :
// Data : 29/08/2020
// Seção de Declarações 
var
   Nota1, nota2, nota3, nota4, media: real
inicio
   escreva("Digite a nota1: ")
   leia(nota1)
   escreva("Digite a nota2: ")
   leia(nota2)
   escreva("Digite a nota3: ")
   leia(nota3)
   escreva("Digite a nota4: ")
   leia(nota4)
   media:= (nota1+nota2+nota3+nota4)/4
   escreva("A média é ", media)
   
fimalgoritmo
