algoritmo "Retornar Maior"
// Função : Ler cinco números e retornar o maior
// Autor : Rafaela Curti de Paula
// Data : 29/08/2020
// Seção de Declarações 
var
   num, maior, contador: inteiro
inicio
      maior:=1045
      para contador de 1 ate 5 faca
           escreva("Digite o valor: ")
           leia(num)
           
           se num > maior entao
              maior:= num
           fimse

      fimpara
      escreva("O maior valor é: ", maior)
fimalgoritmo
